  {"s_SetHostileCommander"  , s_SetHostileCommander, 0},
  {"s_SetFriendlyCommander"  , s_SetFriendlyCommander, 0},
  {"s_DeleteHowitzer", s_DeleteHowitzer, 0 },
  {"s_NewProjectEx",s_NewProjectEx,0},  {"s_RemoveObject"           , s_RemoveObject           , 0},
  {"s_RestartLevel"           , s_RestartLevel           , 0},
  {"s_GetBriefingTime"        , s_GetBriefingTime        , 0},
  {"s_SearchObjectIDNoWarning", s_SearchObjectIDNoWarning, 0},
  {"s_ForceRemoveObject"      , s_ForceRemoveObject      , 0},
