{"lmp_EV_START"      ,    s_Const_lmp_EV_START, 0 },
{"lmp_EV_SETENDPOS"  ,    s_Const_lmp_EV_SETENDPOS, 0 },
{"s_lev_LOAD",            s_lev_LOAD,    0},
{"s_lev_SAVE",            s_lev_SAVE,    0},
{"s_lev_RESTART",         s_lev_RESTART, 0},{"s_SndVol"                    , s_Const_s_SndVol                    , 0},
{"pe_EVCMD_START_EX"           , s_Const_pe_EVCMD_START_EX           , 0},
{"taxi_SET_TO_POS"             , s_Const_taxi_SET_TO_POS             , 0},
{"train_EV_ATTACH"             , s_Const_train_EV_ATTACH             , 0},
{"train_EV_ATTACH_SMOKER"      , s_Const_train_EV_ATTACH_SMOKER      , 0},
{"train_EV_SETPAUSE"           , s_Const_train_EV_SETPAUSE           , 0},
{"train_EV_ADDCANNON"          , s_Const_train_EV_ADDCANNON          , 0},
{"rc_SET_VIDEO"                , s_Const_rc_SET_VIDEO                , 0},
{"rc_SET_DEFTAXI"              , s_Const_rc_SET_DEFTAXI              , 0},
{"rc_SET_DICTIONARY"           , s_Const_rc_SET_DICTIONARY           , 0},
{"DESTROYABLE_IMMORTAL_STATE"  , s_Const_DESTROYABLE_IMMORTAL_STATE  , 0},
{"EV_VEHICLE_PRINTMESSAGE"     , s_Const_EV_VEHICLE_PRINTMESSAGE     , 0},
{"EV_VEHICLE_SOUNDEVENT"       , s_Const_EV_VEHICLE_SOUNDEVENT       , 0},
{"EV_VEHICLE_PANELEVENT"       , s_Const_EV_VEHICLE_PANELEVENT       , 0},
